version: "3.3"

services:

  gateway:
    build: DockerfileTest
    image: esswhye/arvent-gateway:latest
    ports:
      - "8010:8080"
    environment:
      SPRING_PROFILES_ACTICE: dt
    networks:
      - arvent_backend
    deploy:
      replicas: 1
      replicas-max-per-node: 1
    volumes:
      - my-arvent:/app

networks:
  arvent_backend:
    external: true

volumes:
  my-arvent:
