version: "3.3"

services:

  gateway:
    build: .
    image: esswhye/arvent-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTICE: dt
    networks:
      - arvent_backend
    deploy:
      replicas: 1
      
networks:
  arvent_backend:
    external: true
