version: "3.3"

services:


  consul:
    image: consul:latest
    ports:
      - 8500:8500

  gateway:
    build:
      context: .
      dockerfile: DockerfileTest
    image: esswhye/arvent-gateway:latest
    ports:
      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTICE: dt
    deploy:
      replicas: 1
    #      placement:
    #        max_replicas_per_node: 1
    depends_on:
      - consul

networks:
  arvent_backend:
