version: "3.8"

services:

  gateway:
    build: DockerfileTest
    image: esswhye/arvent-gateway:latest
    ports:
      - "8010:8081"
    environment:
      SPRING_PROFILES_ACTICE: dt
    networks:
      - arvent_backend
        deploy:
          replicas: 1
          placement:
            max_replicas_per_node: 1
    volumes:
      - my-arvent:/app

networks:
  arvent_backend:
    external:
      name: arvent_backend

volumes:
  my-arvent:
