version: "3.8"

services:

  gateway:
    build:
      context: .
      dockerfile: DockerfileTest
    image: esswhye/arvent-gateway:latest
    ports:
      - "8010:8010"
    depends_on:
      - consul
    environment:
      SPRING_PROFILES_ACTICE: dt
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 888M
    volumes:
      - my-arvent:/app
      - shareclasses:/opt/shareclasses

networks:
  backend:
    external: true
#    name: arvent_backend



volumes:
  my-arvent:
  shareclasses:
  #    depends_on:
  #      - consul