version: "3.8"

services:

  gateway:
    build:
      context: .
      dockerfile: DockerfileTest
    image: esswhye/arvent-gateway:latest
    ports:
      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTICE: dt
    networks:
      - arvent_backend
    #    depends_on:
    #      - consul
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 888M
    #      placement:
    #        max_replicas_per_node: 1
    volumes:
      - my-arvent:/app
      - shareclasses:/opt/shareclasses

networks:
  arvent_backend:
    external: true


volumes:
  my-arvent:
  shareclasses:
