server:
  port: 8080

#endpoints:
#  cors:
#    allow-credentials: true
#    allowed-origins: '*'
#    allowed-headers: Origin, X-Requested-With, Content-Type, Accept, Connection, User-Agent, Cookie, OCB.SYNCER.JSESSIONID
#    allowed-methods: POST,GET,DELETE,PUT
#    max-age: 1800
zuul:
  #prefix: /arvent
  #stripPrefix: true
  #ignored-patterns: /actuator/**
  #ignoredServices: "*"
  retryable: true
  routes:
    #ignored-patterns: /actuator/**

    # Map path to auth service
    auth:
      path: /auth-service/**
      service-id: auth-service
      prefix: false
      sensitive-headers: Cookie,Set-Cookie
    order:
      path: /order-service/**
      serviceId: order-service
    customer:
      path: /customer-service/**
      serviceId: customer-service
    product:
      path: /product-service/**
      serviceId: product-service
    #TEST JWT
    test:
      path: /common-service/**
      serviceId: common-service

 # ribbon-isolation-strategy: thread
   #Default ->
    #sensitiveHeaders: Cookie,Set-Cookie,Authorization,User-Agent
#sensitiveHeaders:
 # host:
  #  connect-timeout-millis: 60000
  #  socket-timeout-millis:  60000

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
  eager-load:
    enabled: true
  maxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 500,404,502,-408

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      #circuitBreaker:
       # enabled: false

order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

customer-service:
    ribbon:
     # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      ReadTimeout: 10000
      ConnectTimeout: 10000

product-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allow-credentials: true
        allowed-origins: '*'
        allowed-headers: Origin, X-Requested-With, Content-Type, Accept, Connection, User-Agent, Cookie, Authorization
        allowed-methods: POST,GET,DELETE,PUT
        max-age: 1800

#  endpoint:
#    health:
#      show-details: always
