server:
  port: 8080

#endpoints:
#  cors:
#    allow-credentials: true
#    allowed-origins: '*'
#    allowed-headers: Origin, X-Requested-With, Content-Type, Accept, Connection, User-Agent, Cookie, OCB.SYNCER.JSESSIONID
#    allowed-methods: POST,GET,DELETE,PUT
#    max-age: 1800
zuul:
  #prefix: /arvent
  #stripPrefix: true
  #ignored-patterns: /actuator/**
  #ignoredServices: "*"
  retryable: true
  routes:
    #ignored-patterns: /actuator/**
    order:
      path: /order-service/**
      serviceId: order-service
    customer:
      path: /customer-service/**
      serviceId: customer-service
    product:
      path: /product-service/**
      serviceId: product-service
 # ribbon-isolation-strategy: thread
   #Default -> sensitiveHeaders: Cookie,Set-Cookie,Authorization
#sensitiveHeaders:
 # host:
  #  connect-timeout-millis: 60000
  #  socket-timeout-millis:  60000
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
  eager-load:
    enabled: true
  maxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 500,404,502,-408

logging:
  level:
    org.springframework: ERROR
    com.arvent: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      #circuitBreaker:
       # enabled: false

order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

customer-service:
    ribbon:
     # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      ReadTimeout: 10000
      ConnectTimeout: 10000

product-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
#  endpoint:
#    health:
#      show-details: always
