server:
  port: 8080
#endpoints:
#  cors:
#    allow-credentials: true
#    allowed-origins: '*'
#    allowed-headers: Origin, X-Requested-With, Content-Type, Accept, Connection, User-Agent, Cookie, OCB.SYNCER.JSESSIONID
#    allowed-methods: POST,GET,DELETE,PUT
#    max-age: 1800
zuul:
  #prefix: /arvent
  #  stripPrefix: true
  ignored-patterns: /actuator/**
  ignoredServices: "*"
  retryable: true
  routes:
    #ignored-patterns: /actuator/**
    order:
      path: /order-service/**
      serviceId: order-service
    customer:
      path: /customer-service/**
      serviceId: customer-service
    product:
      path: /product-service/**
      serviceId: product-service
 # ribbon-isolation-strategy: thread
  #Default -> sensitiveHeaders: Cookie,Set-Cookie,Authorization
#sensitiveHeaders:
 # host:
  #  connect-timeout-millis: 60000
  #  socket-timeout-millis:  60000


#  NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 5000
  maxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 500,404,502

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
      #circuitBreaker:
       # enabled: false

#order-service:
#  ribbon:
#    ReadTimeout: 5000

#customer-service:
#  ribbon:
#    ReadTimeout: 5000

#product-service:
#  ribbon:
#    ReadTimeout: 5000




management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
